services:
  - type: web
    name: restaurant-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: TELEGRAM_BOT_TOKEN
        value: your_telegram_bot_token
      - key: LLM_API_KEY
        value: your_openai_api_key
      - key: STRIPE_SECRET_KEY
        value: your_stripe_secret_key
      - key: STRIPE_WEBHOOK_SECRET
        value: your_stripe_webhook_secret
      - key: CIRCLE_API_KEY
        value: your_circle_api_key
      - key: ADMIN_USDC_ADDRESS
        value: your_admin_usdc_address
      - key: KITCHEN_CHAT_ID
        value: your_kitchen_telegram_chat_id
      - key: DATABASE_URL
        value: your_postgres_database_url
