# File: .github/workflows/render-deploy.yaml
name: 🚀 Deploy to Render

on:
  push:
    branches:
      - main  # or 'master' based on your repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📦 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: 🔧 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
