services:
  - type: web
    name: restaurant-chatbot
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: LLM_API_KEY
        sync: false
      - key: KITCHEN_CHAT_ID
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: BASE_URL
        value: https://api.groq.com/openai/v1

databases:
  - name: restaurant-db
    databaseName: restaurant
    user: restaurant_user
    plan: free