services:
  - type: web
    name: restaurant-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: TELEGRAM_BOT_TOKEN
        value: your_telegram_bot_token
      - key: LLM_API_KEY
        value: your_openai_api_key
      - key: PAYSTACK_SECRET_KEY
        value: your_paystack_secret_key
      - key: KITCHEN_CHAT_ID
        value: your_kitchen_telegram_chat_id
      - key: DATABASE_URL
        value: your_postgres_database_url
